In [ ]:
import numpy as np
np333 = np.arange(10, 241, 10)
np333.resize(2, 3, 4)
print(np333)

[[[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]

 [[130 140 150 160]
  [170 180 190 200]
  [210 220 230 240]]]


In [ ]:
print(np333[0,0,2])

30


In [ ]:
print(np333[0,2])

[ 90 100 110 120]


In [ ]:
print(np333[1, 1:, :2])

[[170 180]
 [210 220]]


In [ ]:
print(np333[:, 1:, 2:])

[[[ 70  80]
  [110 120]]

 [[190 200]
  [230 240]]]
